# Generated by Django 3.2.9 on 2021-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id_natureza_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('cod_natureza_despesa', models.CharField(max_length=8)),
                ('desc_natureza_despesa', models.CharField(max_length=60)),
            ],
        ),
    ]
