# Generated by Django 3.2.9 on 2021-12-19 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aula', '0002_fornecedores_ordens_projetos_vigencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensOrdem',
            fields=[
                ('id_item_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('id_ordem', models.IntegerField()),
                ('produto_servico', models.CharField(max_length=100)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itensordem_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensordem_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensContrato',
            fields=[
                ('id_item_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('id_contrato', models.IntegerField()),
                ('id_item_ordem', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itenscontrato_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itenscontrato_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('objeto', models.CharField(max_length=25)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_prestador', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='aula.fornecedores')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
